version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = [
    "react",
    "vue"
  ]

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = ["github.com/srijan-deepsource/next"]